### ISSUE TITLE
先発のリポジトリkv2_colored_shape_trackerと内容が被っている

### ISSUE THREAD

**Issue by yamacir-kit** [agrirobo/iai_kinect2_installer#1]
どちらが親になっても構わないので統合しておいて下さい

**Comment by forno** [comment]
お前のやつcolored shape trackerの開発用じゃないの？
こっちはただのインストーラのつもりだし、それ以外の何も追加するつもりはないぞ。

**Comment by yamacir-kit** [comment]
分かった
こっちのiai_kinect部分を潰しとく

**Comment by forno** [comment]
@YamaCIR-KIT 解決したなら閉じてくだち

**Comment by forno** [comment]
なかなか閉じられないので閉じます。
